### ISSUE TITLE
Node Red infinite crashes after setup several Matterbridge devices | Temp Sensor

### ISSUE THREAD

**Issue by tt2g89** [sammachin/node-red-matter-bridge#26]
Hi,
I noticed that Node Red had crashes infinitely after setup of about 40 devices. Below is the log on startup. Hope it helps.

OS: Debian via LXC on Proxmox
NR latest release
Matter Bridge: 0.11.2
2024-12-11 10:06:08.842 DEBUG  Transaction          Transaction initialize<c4e6514cd82c3ea7.aggregator.b824bfc0719df143>#3cb locked c4e6514cd82c3ea7.aggregator.b824bfc0719df143.windowCovering.state
2024-12-11 10:06:08.844 DEBUG  Transaction          Transaction initialize<c4e6514cd82c3ea7.aggregator.b824bfc0719df143>#3cb locked c4e6514cd82c3ea7.aggregator.b824bfc0719df143.descriptor.state
2024-12-11 10:06:08.845 DEBUG  Transaction          Transaction reactor<c4e6514cd82c3ea7.descriptor.#updatePartsList>#3cc locked c4e6514cd82c3ea7.descriptor.state
2024-12-11 10:06:08.845 DEBUG  Transaction          Transaction reactor<c4e6514cd82c3ea7.aggregator.descriptor.#updatePartsList>#3cd locked c4e6514cd82c3ea7.aggregator.descriptor.state
2024-12-11 10:06:08.846 DEBUG  Transaction          Transaction reactor<c4e6514cd82c3ea7.descriptor.#updatePartsList>#3cc committed and unlocked 1 resource
2024-12-11 10:06:08.846 DEBUG  Transaction          Transaction reactor<c4e6514cd82c3ea7.aggregator.descriptor.#updatePartsList>#3cd committed and unlocked 1 resource
2024-12-11 10:06:08.848 DEBUG  Transaction          Transaction initialize<c4e6514cd82c3ea7.aggregator.b824bfc0719df143>#3cb locked c4e6514cd82c3ea7.aggregator.b824bfc0719df143.bridgedDeviceBasicInformation.state
2024-12-11 10:06:08.850 DEBUG  WindowCoveringServer Operational status changed to {"global":0,"lift":0,"tilt":"undefined"} with new global status undefined
2024-12-11 10:06:08.851 DEBUG  WindowCoveringServer Operational status changed to {"global":0,"lift":0,"tilt":"undefined"} with new global status undefined
2024-12-11 10:06:08.852 DEBUG  Transaction          Transaction initialize<c4e6514cd82c3ea7.aggregator.b824bfc0719df143>#3cb committed and unlocked 4 resources
2024-12-11 10:06:08.856 INFO   Endpoint             c4e6514cd82c3ea7.aggregator.b824bfc0719df143 ready endpoint#: 37 type: WindowCovering (0x202) behaviors: ✓identify ✓bridgedDeviceBasicInformation ✓windowCovering ✓descriptor
11 Dec 10:06:08 - [info] [matteronoffsocket:Strom Terrasse] Registering Child......
11 Dec 10:06:08 - [info] [matterbridge:Matterbridge Node Red] Registering abbb308e123d269e with c4e6514cd82c3ea7
11 Dec 10:06:08 - [info] [matterbridge:Matterbridge Node Red] adding new device to aggregator
11 Dec 10:06:08 - [info] [matterbridge:Matterbridge Node Red] Checking if ready to start
11 Dec 10:06:08 - [info] [matterbridge:Matterbridge Node Red] Starting Bridge
2024-12-11 10:06:08.858 DEBUG  Transaction          Transaction initialize<c4e6514cd82c3ea7.aggregator.abbb308e123d269e>#3e2 locked c4e6514cd82c3ea7.aggregator.abbb308e123d269e.identify.state
2024-12-11 10:06:08.859 WARN   ValidatedElements    Error in IdentifyServer.triggerEffect: Throws unimplemented exception
2024-12-11 10:06:08.859 DEBUG  Transaction          Transaction initialize<c4e6514cd82c3ea7.aggregator.abbb308e123d269e>#3e2 locked c4e6514cd82c3ea7.aggregator.abbb308e123d269e.groups.state
2024-12-11 10:06:08.860 DEBUG  Transaction          Transaction initialize<c4e6514cd82c3ea7.aggregator.abbb308e123d269e>#3e2 locked c4e6514cd82c3ea7.aggregator.abbb308e123d269e.onOff.state
2024-12-11 10:06:08.862 NOTICE Node                 c4e6514cd82c3ea7 going online
2024-12-11 10:06:08.865 DEBUG  Transaction          Transaction initialize<c4e6514cd82c3ea7.aggregator.abbb308e123d269e>#3e2 locked c4e6514cd82c3ea7.aggregator.abbb308e123d269e.descriptor.state
2024-12-11 10:06:08.866 DEBUG  Transaction          Transaction reactor<c4e6514cd82c3ea7.descriptor.#updatePartsList>#3e3 locked c4e6514cd82c3ea7.descriptor.state
2024-12-11 10:06:08.866 DEBUG  Transaction          Transaction reactor<c4e6514cd82c3ea7.aggregator.descriptor.#updatePartsList>#3e4 locked c4e6514cd82c3ea7.aggregator.descriptor.state
2024-12-11 10:06:08.866 DEBUG  Transaction          Transaction reactor<c4e6514cd82c3ea7.descriptor.#updatePartsList>#3e3 committed and unlocked 1 resource
2024-12-11 10:06:08.867 DEBUG  Transaction          Transaction reactor<c4e6514cd82c3ea7.aggregator.descriptor.#updatePartsList>#3e4 committed and unlocked 1 resource
2024-12-11 10:06:08.868 DEBUG  Transaction          Transaction initialize<c4e6514cd82c3ea7.aggregator.abbb308e123d269e>#3e2 locked c4e6514cd82c3ea7.aggregator.abbb308e123d269e.bridgedDeviceBasicInformation.state
2024-12-11 10:06:08.869 DEBUG  Transaction          Transaction initialize<c4e6514cd82c3ea7.aggregator.abbb308e123d269e>#3e2 committed and unlocked 5 resources
2024-12-11 10:06:08.870 INFO   Endpoint             c4e6514cd82c3ea7.aggregator.abbb308e123d269e ready endpoint#: 38 type: OnOffPlugInUnit (0x10a) behaviors: ✓identify ✓groups ✓onOff ✓bridgedDeviceBasicInformation ✓descriptor
2024-12-11 10:06:08.871 DEBUG  UdpChannelNode       Socket created and bound remoteAddress: undefined:5353 localAddress: 0.0.0.0:5353
2024-12-11 10:06:08.872 DEBUG  UdpChannelNode       Initialize multicast address: 192.168.0.101:5353 interface: eth0 type: udp4
2024-12-11 10:06:08.872 DEBUG  UdpChannelNode       Socket created and bound remoteAddress: undefined:5353 localAddress: :::5353
2024-12-11 10:06:08.872 DEBUG  UdpChannelNode       Initialize multicast address: ::%eth0:5353 interface: eth0 type: udp6
2024-12-11 10:06:08.873 DEBUG  UdpChannelNode       Socket created and bound remoteAddress: undefined:5353 localAddress: 0.0.0.0:5353
2024-12-11 10:06:08.873 DEBUG  UdpChannelNode       Initialize multicast address: 192.168.0.101:5353 interface: eth0 type: udp4
2024-12-11 10:06:08.874 DEBUG  UdpChannelNode       Socket created and bound remoteAddress: undefined:5353 localAddress: :::5353
2024-12-11 10:06:08.874 DEBUG  UdpChannelNode       Initialize multicast address: ::%eth0:5353 interface: eth0 type: udp6
2024-12-11 10:06:08.875 DEBUG  UdpChannelNode       Socket created and bound remoteAddress: undefined:5540 localAddress: :::5540
2024-12-11 10:06:08.876 DEBUG  Transaction          Transaction set<c4e6514cd82c3ea7>#3f3 locked c4e6514cd82c3ea7.network.state
2024-12-11 10:06:08.876 DEBUG  Transaction          Transaction set<c4e6514cd82c3ea7>#3f3 committed and unlocked 1 resource
2024-12-11 10:06:08.876 DEBUG  UdpChannelNode       Socket created and bound remoteAddress: undefined:5540 localAddress: 0.0.0.0:5540
2024-12-11 10:06:08.892 DEBUG  DeviceAdvertiser     Announcing fabric: 3961506689
2024-12-11 10:06:08.892 DEBUG  DeviceAdvertiser     Announcing fabric: 3472809503
2024-12-11 10:06:08.892 DEBUG  DeviceAdvertiser     Announcing fabric: 98010128742473474
2024-12-11 10:06:08.893 DEBUG  MdnsBroadcaster      Announcement Generator: Fabric id: cd0014e29abdda79/2666361215 qname: CD0014E29ABDDA79-000000009EED717F._matter._tcp.local port: 5540 interface: eth0
2024-12-11 10:06:08.894 DEBUG  MdnsBroadcaster      Announcement Generator: Fabric id: 0dde91b247c1e5eb/676192756 qname: 0DDE91B247C1E5EB-00000000284DE1F4._matter._tcp.local port: 5540 interface: eth0
2024-12-11 10:06:08.894 DEBUG  MdnsBroadcaster      Announcement Generator: Fabric id: 02c8b96f6b4debc9/301390058571383472 qname: 02C8B96F6B4DEBC9-042EC0A953FB42B0._matter._tcp.local port: 5540 interface: eth0
2024-12-11 10:06:08.897 NOTICE Node                 c4e6514cd82c3ea7 is online
2024-12-11 10:06:08.897 DEBUG  EventHandler         Received event: {"eventNumber":"1","eventId":0,"clusterId":40,"endpointId":0,"epochTimestamp":1733907968897,"priority":2,"data":{"softwareVersion":0}}
2024-12-11 10:06:08.899 INFO   AccessControlServer  initializing ACL manager with ACL { privilege: 5, authMode: 2, subjects: [ 1995503845 ], targets: null, fabricIndex: 2 } { privilege: 5, authMode: 2, subjects: [ 18446744061111435265, 3628294924 ], targets: null, fabricIndex: 1 } { privilege: 3, authMode: 2, subjects: [ 18446744062914002945 ], targets: null, fabricIndex: 1 } { privilege: 5, authMode: 2, subjects: [ 18446744060825763887, 18446744060824715265 ], targets: null, fabricIndex: 3 }
2024-12-11 10:06:08.900 DEBUG  Transaction          Transaction offline#3f6 locked c4e6514cd82c3ea7.operationalCredentials.state
2024-12-11 10:06:08.901 DEBUG  Transaction          Transaction offline#3f6 committed and unlocked 1 resource
2024-12-11 10:06:08.901 DEBUG  Transaction          Transaction offline#3f6 locked c4e6514cd82c3ea7.operationalCredentials.state and c4e6514cd82c3ea7.generalDiagnostics.state
2024-12-11 10:06:08.901 DEBUG  EventHandler         Received event: {"eventNumber":"2","eventId":3,"clusterId":51,"endpointId":0,"epochTimestamp":1733907968901,"priority":2,"data":{"bootReason":0}}
2024-12-11 10:06:08.903 DEBUG  Transaction          Transaction offline#3f6 locked c4e6514cd82c3ea7.commissioning.state
2024-12-11 10:06:08.903 DEBUG  Transaction          Transaction offline#3f6 committed and unlocked 3 resources
11 Dec 10:06:08 - [info] [matterbridge:Matterbridge Node Red] Server Started
2024-12-11 10:06:08.904 DEBUG  UdpChannelNode       Socket created and bound remoteAddress: undefined:5353 localAddress: 0.0.0.0:5353
2024-12-11 10:06:08.905 DEBUG  UdpChannelNode       Socket created and bound remoteAddress: undefined:5353 localAddress: :::5353
2024-12-11 10:06:08.905 DEBUG  UdpChannelNode       Initialize multicast address: 192.168.0.101:5353 interface: eth0 type: udp4
2024-12-11 10:06:08.905 DEBUG  UdpChannelNode       Initialize multicast address: ::%eth0:5353 interface: eth0 type: udp6
2024-12-11 10:06:08.930 DEBUG  MdnsScanner          Adding operational device CD0014E29ABDDA79-000000009EED717F._matter._tcp.local in cache (interface eth0, ttl=120) with TXT data: SII: 500 SAI: 300 SAT: 4000 T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
2024-12-11 10:06:08.971 DEBUG  Transaction          Transaction set<c4e6514cd82c3ea7.aggregator.bb2687251f7f397d>#3f7 locked c4e6514cd82c3ea7.aggregator.bb2687251f7f397d.temperatureMeasurement.state
2024-12-11 10:06:08.972 ERROR  Transaction          State has not settled after 5 pre-commit cycles which likely indicates an infinite loop
2024-12-11 10:06:08.972 DEBUG  Transaction          Transaction set<c4e6514cd82c3ea7.aggregator.bb2687251f7f397d>#3f7 rolled back and unlocked 1 resource
2024-12-11 10:06:08.972 FATAL  Logger               Unhandled error detected: Rolled back due to pre-commit error
  at errorRollback (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:341:13)
  at nextCycle (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:349:16)
  at nextPreCommit (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:365:28)
  at #executePreCommit (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:392:12)
  at Tx.commit (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:256:42)
  at commitTransaction (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:49:23)
  at async Endpoint.set (/root/.node-red/node_modules/@matter/node/dist/cjs/endpoint/Endpoint.js:160:5)
11 Dec 10:06:08 - [red] Uncaught Exception:
11 Dec 10:06:08 - [error] Error: Rolled back due to pre-commit error
    at errorRollback (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:341:13)
    at nextCycle (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:349:16)
    at nextPreCommit (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:365:28)
    at #executePreCommit (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:392:12)
    at Tx.commit (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:256:42)
    at commitTransaction (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:49:23)
    at async Endpoint.set (/root/.node-red/node_modules/@matter/node/dist/cjs/endpoint/Endpoint.js:160:5)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.

**Comment by tt2g89** [comment]
I’ve found out that NR crashes because of a temperature sensor device.

**Comment by sammachin** [comment]
@tt2g89 can you share the config of your temperature sensor?

Also does it still crash with only that device/flow enabled?

**Comment by tt2g89** [comment]
Hi @sammachin,
I used the standard configuration.
I’ve tried different things:
### With current, working configuration:
**1.a. I’ve deployed another bridge with only this temp sensor. The first bridge deactivated. That went well, bridge started.
1.b. Reactivated the first bridge, too. Also fine.
1.c. Attached Temp sensor again to first bridge. Works... Cannot reproduce the topic for now. :(** 
### Restored backup with malicious configuration. 
**2.a. Started - infinite boot attempts**
**2.b. Safe-start of NR and attach Temp-sensor to another bridge - infinite boot attempts:**
`12 Dec 14:56:53 - [info] [matterbridge:Matterbridge Node Red] Server Started
2024-12-12 14:56:53.588 ERROR  Transaction          State has not settled after 5 pre-commit cycles which likely indicates an infinite loop
2024-12-12 14:56:53.589 FATAL  Logger               Unhandled error detected: Rolled back due to pre-commit error
  at errorRollback (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:341:13)
  at nextCycle (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:349:16)
  at nextPreCommit (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:365:28)
  at #executePreCommit (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:392:12)
  at Tx.commit (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:256:42)
  at commitTransaction (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:49:23)
  at runNextTicks (node:internal/process/task_queues:60:5)
  at process.processImmediate (node:internal/timers:454:9)
  at async Endpoint.set (/root/.node-red/node_modules/@matter/node/dist/cjs/endpoint/Endpoint.js:160:5)
12 Dec 14:56:53 - [red] Uncaught Exception:
12 Dec 14:56:53 - [error] Error: Rolled back due to pre-commit error
    at errorRollback (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:341:13)
    at nextCycle (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:349:16)
    at nextPreCommit (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:365:28)
    at #executePreCommit (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:392:12)
    at Tx.commit (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:256:42)
    at commitTransaction (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:49:23)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:454:9)
    at async Endpoint.set (/root/.node-red/node_modules/@matter/node/dist/cjs/endpoint/Endpoint.js:160:5)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.`

**2.c. Safe-start of NR and deactivation of all other Matterbridge-nodes - infinite boots**
`2024-12-12 15:03:36.616 ERROR  Transaction          State has not settled after 5 pre-commit cycles which likely indicates an infinite loop
2024-12-12 15:03:36.618 FATAL  Logger               Unhandled error detected: Rolled back due to pre-commit error
  at errorRollback (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:341:13)
  at nextCycle (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:349:16)
  at nextPreCommit (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:365:28)
  at #executePreCommit (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:392:12)
  at Tx.commit (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:256:42)
  at commitTransaction (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:49:23)
  at async Endpoint.set (/root/.node-red/node_modules/@matter/node/dist/cjs/endpoint/Endpoint.js:160:5)
12 Dec 15:03:36 - [red] Uncaught Exception:
12 Dec 15:03:36 - [error] Error: Rolled back due to pre-commit error
    at errorRollback (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:341:13)
    at nextCycle (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:349:16)
    at nextPreCommit (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:365:28)
    at #executePreCommit (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:392:12)
    at Tx.commit (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:256:42)
    at commitTransaction (/root/.node-red/node_modules/@matter/node/dist/cjs/behavior/state/transaction/Tx.js:49:23)
    at async Endpoint.set `(/root/.node-red/node_modules/@matter/node/dist/cjs/endpoint/Endpoint.js:160:5)`
**2.d.** safe start of NR, renamed Haustür to Haustuer - same
**2.e. Safe start of NR, deletion of that node and creation of the same node - same.
**2.e. Safe start of NR, deletion of link to incoming signal - works. There is a zigbee2mqtt device and a function which maybe send the wrong type of information which causes the crashes. If you need more information on what caused the crashes, let me know, which. Maybe that helps to make the devices more robust. 


Side note: Also with stable config there are always devices that are not responding in HomeKit, no clue why. They’re also changing. Is there a limit of devices per bridge?

BR,
Tom

**Comment by sammachin** [comment]
So its only when you send data into the temp sensor node that it crashes? it would be good to know what you're sending.

In terms of devices not responding in HomeKit, I have seen that Matter generally takes a little while for a controller to get updates for everything so if you're doing a lot of restarts it can show as not responding as the session needs to timeout and retry, But it should all settle down and run after 15mins or so.

I've tested bridges with 64 devices on them no problem, Matter in theory can support 16K! What I did notice was that 64 devices was all being a bit slow to respond/update when the bridge was running on a Pi3 but it was fine on my Mac Studio.

**Comment by tt2g89** [comment]
That was the payload it received and which crashed NR (Zigbee2MQTT is set up to send a value at start):
`zigbee2mqtt/Sensor_Move_Haustuer : msg.payload : Object
object
temperature: -0.45
scale: "CELSIUS"`

Ok, my Pi3 is already retired and I switched to an Intel machine with Proxmox with a bit more power, but it’s not running too smooth at the moment.
I tried a setup with three bridges, but only the first worked fine, even after two hours of not touching anything. Forgot to extract the logs. Now the backup is restored and I’m back on only one bridge-setup and 50 devices on it.
The WAF is around 0.5 on a 0-10 scale, but you mentioned in the readme, that this is still experimental. 😉

Here are the last logs and there are still at least warnings regarding exceptions. Is this a behavior that you have, too?

`12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] Checking if ready to start
2024-12-12 20:41:19.853 WARN   ValidatedElements    Error in IdentifyServer.triggerEffect: Throws unimplemented exception
2024-12-12 20:41:19.860 INFO   Endpoint             c4e6514cd82c3ea7.aggregator.5137f31038760187 ready endpoint#: 47 type: OnOffPlugInUnit (0x10a) behaviors: ✓identify ✓groups ✓onOff ✓bridgedDeviceBasicInformation ✓descriptor
12 Dec 20:41:19 - [info] [matterdimmablelight:Büro Iris] Registering Child......
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] Registering b3d1ac3587bd3f49 with c4e6514cd82c3ea7
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] adding new device to aggregator
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] Checking if ready to start
2024-12-12 20:41:19.872 WARN   ValidatedElements    Error in IdentifyServer.triggerEffect: Throws unimplemented exception
2024-12-12 20:41:19.884 INFO   Endpoint             c4e6514cd82c3ea7.aggregator.b3d1ac3587bd3f49 ready endpoint#: 29 type: DimmableLight (0x101) behaviors: ✓identify ✓groups ✓onOff ✓levelControl ✓bridgedDeviceBasicInformation ✓descriptor
12 Dec 20:41:19 - [info] [matterwindowcovering:Büro Iris West] Registering Child......
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] Registering 1a897eadb1c3add0 with c4e6514cd82c3ea7
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] adding new device to aggregator
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] Checking if ready to start
2024-12-12 20:41:19.898 INFO   Endpoint             c4e6514cd82c3ea7.aggregator.1a897eadb1c3add0 ready endpoint#: 31 type: WindowCovering (0x202) behaviors: ✓identify ✓bridgedDeviceBasicInformation ✓windowCovering ✓descriptor
12 Dec 20:41:19 - [info] [matterwindowcovering:Büro Iris Süd] Registering Child......
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] Registering 200e0960a9a986fd with c4e6514cd82c3ea7
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] adding new device to aggregator
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] Checking if ready to start
2024-12-12 20:41:19.907 INFO   Endpoint             c4e6514cd82c3ea7.aggregator.200e0960a9a986fd ready endpoint#: 32 type: WindowCovering (0x202) behaviors: ✓identify ✓bridgedDeviceBasicInformation ✓windowCovering ✓descriptor
12 Dec 20:41:19 - [info] [matteronoffsocket:Badspiegel] Registering Child......
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] Registering 6120dc8073070f89 with c4e6514cd82c3ea7
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] adding new device to aggregator
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] Checking if ready to start
2024-12-12 20:41:19.909 WARN   ValidatedElements    Error in IdentifyServer.triggerEffect: Throws unimplemented exception
2024-12-12 20:41:19.915 INFO   Endpoint             c4e6514cd82c3ea7.aggregator.6120dc8073070f89 ready endpoint#: 33 type: OnOffPlugInUnit (0x10a) behaviors: ✓identify ✓groups ✓onOff ✓bridgedDeviceBasicInformation ✓descriptor
12 Dec 20:41:19 - [info] [matterdimmablelight:Bad] Registering Child......
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] Registering f3081c7b8e14949b with c4e6514cd82c3ea7
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] adding new device to aggregator
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] Checking if ready to start
2024-12-12 20:41:19.920 WARN   ValidatedElements    Error in IdentifyServer.triggerEffect: Throws unimplemented exception
2024-12-12 20:41:19.928 INFO   Endpoint             c4e6514cd82c3ea7.aggregator.f3081c7b8e14949b ready endpoint#: 34 type: DimmableLight (0x101) behaviors: ✓identify ✓groups ✓onOff ✓levelControl ✓bridgedDeviceBasicInformation ✓descriptor
12 Dec 20:41:19 - [info] [matteronofflight:Terrasse] Registering Child......
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] Registering 14679b5374f76dd1 with c4e6514cd82c3ea7
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] adding new device to aggregator
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] Checking if ready to start
2024-12-12 20:41:19.930 WARN   ValidatedElements    Error in IdentifyServer.triggerEffect: Throws unimplemented exception
2024-12-12 20:41:19.941 INFO   Endpoint             c4e6514cd82c3ea7.aggregator.14679b5374f76dd1 ready endpoint#: 35 type: OnOffLight (0x100) behaviors: ✓identify ✓groups ✓onOff ✓bridgedDeviceBasicInformation ✓descriptor
12 Dec 20:41:19 - [info] [matterfullcolorlight:Whirlpool] Registering Child......
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] Registering 36726a4f9afc7252 with c4e6514cd82c3ea7
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] adding new device to aggregator
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] Checking if ready to start
2024-12-12 20:41:19.949 WARN   ValidatedElements    Error in IdentifyServer.triggerEffect: Throws unimplemented exception
2024-12-12 20:41:19.963 INFO   Endpoint             c4e6514cd82c3ea7.aggregator.36726a4f9afc7252 ready endpoint#: 36 type: ColorTemperatureLight (0x10c) behaviors: ✓identify ✓groups ✓onOff ✓levelControl ✓colorControl ✓bridgedDeviceBasicInformation ✓descriptor
12 Dec 20:41:19 - [info] [matterwindowcovering:Markise] Registering Child......
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] Registering b824bfc0719df143 with c4e6514cd82c3ea7
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] adding new device to aggregator
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] Checking if ready to start
2024-12-12 20:41:19.981 INFO   Endpoint             c4e6514cd82c3ea7.aggregator.b824bfc0719df143 ready endpoint#: 37 type: WindowCovering (0x202) behaviors: ✓identify ✓bridgedDeviceBasicInformation ✓windowCovering ✓descriptor
12 Dec 20:41:19 - [info] [matteronoffsocket:Strom Terrasse] Registering Child......
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] Registering abbb308e123d269e with c4e6514cd82c3ea7
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] adding new device to aggregator
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] Checking if ready to start
12 Dec 20:41:19 - [info] [matterbridge:Matterbridge-Node-RED] Starting Bridge
2024-12-12 20:41:19.983 WARN   ValidatedElements    Error in IdentifyServer.triggerEffect: Throws unimplemented exception
2024-12-12 20:41:19.987 NOTICE Node                 c4e6514cd82c3ea7 going online
2024-12-12 20:41:19.994 INFO   Endpoint             c4e6514cd82c3ea7.aggregator.abbb308e123d269e ready endpoint#: 38 type: OnOffPlugInUnit (0x10a) behaviors: ✓identify ✓groups ✓onOff ✓bridgedDeviceBasicInformation ✓descriptor
2024-12-12 20:41:20.025 NOTICE Node                 c4e6514cd82c3ea7 is online
2024-12-12 20:41:20.033 INFO   AccessControlServer  initializing ACL manager with ACL { privilege: 5, authMode: 2, subjects: [ 1995503845 ], targets: null, fabricIndex: 2 } { privilege: 5, authMode: 2, subjects: [ 18446744061111435265, 3628294924 ], targets: null, fabricIndex: 1 } { privilege: 3, authMode: 2, subjects: [ 18446744062914002945 ], targets: null, fabricIndex: 1 } { privilege: 5, authMode: 2, subjects: [ 18446744060825763887, 18446744060824715265 ], targets: null, fabricIndex: 3 }****`

**Comment by sammachin** [comment]
Ok I’ll take a look with that payload.

You won’t be able to run more than one bridge on a node-red instance unless you have multiple network interfaces, as it binds to the port.

You can ignore the warnings about identify trigger effect I should either handle those with a null function or get matter.js to disable them

**Comment by tt2g89** [comment]
Thanks, Sam!

Ok, that makes sense. I could give my VM a second IF, but if you are using more than 60 devices via one bridge, I’ll check this out again, too.

Thanks for your great work, Sam! I’ve waited very long for a Node-Red driven solution and I’m happy to see that it works quite well. :-)

**Comment by sammachin** [comment]
Yeah I think if it’s the same machine and the same network bandwidth then there likely won’t be much difference in one bridge of 50 devices be 2 of 25.

Some of this is also down to the protocol and the controllers, Matter is still quite new and things are being worked out. Hartley anyone will have 50 real matter devices in their home yet!

**Comment by tt2g89** [comment]
Don’t think so, too. :D 

Just checked, if it basically works and it does fine, just fyi.

**Comment by sammachin** [comment]
@tt2g89 Right in terms of the crash its because your payload is an object, the temperature sensor expects mag.payload to be a number between -273.15 and 327.67
Matter always uses Celsius for its values.

I should add some validation to the inputs though to catch that rather than passing it up to Matter.js

**Comment by sammachin** [comment]
I've added some input validation and catching of errors in 0.11.3 so this should no longer crash node-red
